import './css/homepage.css';
import './css/bootstrap.min.css';
import './css/fonts.css';
// import './js/bootstrap.min.js';
// import './js/popper.min.js';
// import './js/slim.min.js';
// import About from "src/app/about_us";
import Link from 'next/link';

export const metadata = {
  title: 'Umer Next',
  description: 'Generated by HA-DEVELOPER',
}

const index = () => {
  return (
    <>
      <body>
        <div className="topwritting">
          <h3>Zestful Amigos</h3>
        </div>

        <div className="header" id="topheader">
          <nav className="navbar navbar-expand-lg  navbar-dark">
            <div className="container text-uppercase p-2 text-c">
              <Link href="/">
                <div className="navbar-brand font-weight-bold "></div>
              </Link>
              <button className="navbar-toggler text-primary" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav m-auto text-uppercase ">
                  <li className="nav-item active ml-3 mr-3">
                    <Link href="home">
                      <div className="nav-link text-white">Home</div>
                    </Link>
                  </li>
                  <div className="dropdown">
                    <button className="dropbtn">Dropdown</button>
                    <div className="dropdown-content">
                      <Link href="/about_us">
                        <div>about us</div>
                      </Link>
                      <a href="privacy">privacy policy</a>
                    </div>
                  </div>
                  <li className="nav-item ml-3 mr-3">
                    <Link href="/contact_us">
                      <div className="nav-link text-white">Contact</div>
                    </Link>
                  </li>
                  <li className="nav-item ml-3 mr-3">
                    <Link href="/services">
                      <div className="nav-link text-white">service</div>
                    </Link>
                  </li>
                  <li className="nav-item ml-3 mr-3">
                    <Link href="/employment_form">
                      <div className="nav-link text-white">employment</div>
                    </Link>
                  </li>
                </ul>
                <div>
                  <a href="logout"><button type="button" className="btn btn-danger">LOGOUT</button></a>
                  <button type="button" className="btn btn-danger mx-2" data-toggle="modal"
                    data-target="#loginModal">LOGIN</button>
                  <a href="register"><button type="button" className="btn btn-danger">SIGNUP</button></a>
                </div>
              </div>
            </div>

          </nav>
        </div>

        <div className="container mt-3">
          <div className="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <button type="button" className="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>

        {/* loginModal */}
        <div className="containerx my-4">
          <div className="form-group">
            {/*  Display User details  */}
            <h2>User Details</h2>
            <p><strong>Username:</strong> username</p>
            <p><strong>Email:</strong> user email </p>
            {/*  Add other User fields you want to display here  */}
            <h2>Edit Profile Details</h2>
            <form method="post">
              <button type="submit">Update Profile</button>
            </form>
          </div>
        </div>

        <footer>
          <div className="container">
            <p className="float-end"><Link href="/">Back to Top</Link></p>
            <p>© Zestful Amigos Company, Zestful.inc · </p>
          </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossOrigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossOrigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossOrigin="anonymous"></script>
      </body>
    </>
  );
};

export default index;