import Script from "next/script";
// Style
import "../css/homepage.css";
import '../css/bootstrap.min.css';
import '../css/fonts.css';
import './globals.css';
import '../css/mysite.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Umer Next - Home',
  description: 'Generated by HA-DEVELOPER',
  manifest:'/manifest.webmanifest'
}

const RootLayout = ({ children }) => {
  return (
    <html>
      <body>
        {children}


        <Script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></Script>
        <Script src="https://kit.fontawesome.com/2c865cf201.js" crossorigin="anonymous"></Script>
      </body >
    </html >
  );
};

export default RootLayout;