# Generated by Django 4.1.7 on 2023-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employmentform_profile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentform',
            name='references',
        ),
        migrations.AddField(
            model_name='employmentform',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='employmentform',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentform',
            name='languages',
            field=models.TextField(default='English'),
        ),
        migrations.AddField(
            model_name='employmentform',
            name='photo_body',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employmentform',
            name='photo_face',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employmentform',
            name='what_makes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
