# Generated by Django 4.1.7 on 2023-08-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq_alter_userrequest_preferred_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='type_of_companion',
            field=models.CharField(choices=[('virtual', 'Virtual (Phone / Text)'), ('in_person', 'In Person')], max_length=100),
        ),
    ]
