# Generated by Django 4.1.7 on 2023-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userrequest_type_of_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='type_of_companion',
            field=models.CharField(choices=[('virtual', 'Virtual (Phone / Text)'), ('in_person', 'In Person')], default='in_person', max_length=100),
        ),
    ]
