# Generated by Django 4.1.7 on 2023-08-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_age'),
        ('main', '0007_userrequest_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='companion_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
