# Generated by Django 4.1.7 on 2023-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userrequest_companion_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentform',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
