# Generated by Django 4.2.6 on 2023-10-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_companion_for'),
        ('main', '0010_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentform',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
