# Generated by Django 4.2.6 on 2023-10-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_companion_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companion_for',
        ),
    ]
